name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build_test_publish_amd64:
    name: Build/Test/Publish amd64
    runs-on: ubuntu-lates
    strategy:
      matrix:
        architecture: ["amd64"]
        include:
          - package: package-1
            tenant: ""
          - package: package-2
            tenant: ""
          - package: package-3
            tenant: "t1"
          - package: package-4
            tenant: "t2"
          - package: package-5
            tenant: ""
    steps:
      - name: Build ${{ matrix.package }} (${{ matrix.architecture }})
        run: echo ./stack build --skip-existing-image --architecture=${{ matrix.architecture }} --tenant=${{matrix.tenant}} ${{ matrix.package }}
