name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build_test_publish_amd64:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: package-1
            tenant: ""
            architecture: "amd64"
          - package: package-2
            tenant: ""
            architecture: "amd64"
          - package: package-3
            tenant: "t1"
            architecture: "amd64"
          - package: package-4
            tenant: "t2"
            architecture: "amd64"
          - package: package-5
            tenant: ""
            architecture: "amd64"
    steps:
      - name: Build ${{ matrix.package }} (tenant=${{matrix.tenant}} arch=${{ matrix.architecture }})
        run: echo ./stack build --skip-existing-image --architecture=${{ matrix.architecture }} --tenant="${{matrix.tenant}}" ${{ matrix.package }}

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tenant: "t1"
            packages: "package-1 package-2 package-3"
          - tenant: "t2"
            packages: "package-1 package-2 package-4"
    steps:
      - name: Deploy ${{ matrix.tenant }} (packages=${{matrix.packages}})
        run: echo ./stack deploy --tenant="${{matrix.tenant}}" ${{ matrix.packages }}
